// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $container;
    $container = $('.isotope-container');
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.post-item'
      });
    });
  });

}).call(this);
