// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $dropdownToggle, $overlayTrigger;
    $dropdownToggle = $('.dropdown-toggle');
    $overlayTrigger = $('.overlay-trigger');
    $dropdownToggle.click(function(e) {
      e.preventDefault();
      $(this).parent().find('.dropdown').toggleClass('hidden');
    });
    $overlayTrigger.hover(function() {
      $('.overlay').addClass('bg-global-color-op');
    }, function() {
      $('.overlay').removeClass('bg-global-color-op');
    });
    $('.header').headroom();
  });

}).call(this);
