// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $('.site-content').css({
      marginTop: $(window).height()
    });
  });

}).call(this);
