// Generated by CoffeeScript 1.8.0
(function() {
  var reset, scrollControl;

  $(document).ready(function() {
    var $dropdownToggle, $overlayTrigger, $overlayWork, $scrollDetectOps;
    $dropdownToggle = $('.dropdown-toggle');
    $overlayTrigger = $('.overlay-trigger.overlay-us');
    $overlayWork = $('.overlay-trigger.overlay-work');
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $(document).on('scroll', scrollControl);
    $dropdownToggle.click(function(e) {
      e.preventDefault();
      $(this).parent().find('.dropdown').toggleClass('hidden');
    });
    $overlayTrigger.hover(function() {
      $('.overlay').addClass('bg-info-op');
    }, function() {
      $('.overlay').removeClass('bg-info-op');
    });
    $overlayWork.hover(function() {
      $('.overlay').addClass('bg-success-op');
    }, function() {
      $('.overlay').removeClass('bg-success-op');
    });
    $scrollDetectOps = {
      tolerance: {
        up: 0,
        down: 35
      },
      classes: {
        initial: "scroll-detect",
        pinned: "scroll-detect--up",
        unpinned: "scroll-detect--down",
        top: "scroll-detect--top",
        notTop: "scroll-detect--not-top"
      },
      onPin: function() {},
      onUnpin: function() {},
      onTop: function() {
        return $('.site-wrapper').removeClass('scroll-detect--up');
      },
      onNotTop: function() {}
    };
  });

  reset = 0;

  scrollControl = function() {
    var opacity, winScroll;
    winScroll = $(window).scrollTop();
    reset = winScroll / 2;
    opacity = 1 - (reset / 100);
    if (winScroll > 140) {
      return;
    } else {
      $('.on-scroll').velocity({
        translateY: -reset + 'px',
        opacity: opacity
      }, {
        duration: 0,
        easing: 'ease-in'
      });
    }
  };

}).call(this);
