// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var headerController, headerScene, myPlayer, parallaxController, parallaxScene, scrollToController, tween, videoOnScroll, videoOnScrollController, videoOnScrollScene;
    headerController = new ScrollMagic();
    parallaxController = new ScrollMagic();
    scrollToController = new ScrollMagic();
    videoOnScrollController = new ScrollMagic();
    headerScene = new ScrollScene({
      triggerElement: '.header-trigger',
      triggerHook: 0.2
    }).setClassToggle('.header', 'header-off').addTo(headerController);
    tween = TweenMax.fromTo(".on-scroll", 1, {
      top: 0,
      opacity: 1
    }, {
      top: -350,
      opacity: 0.3
    }, {
      ease: Linear.easeNone
    });
    parallaxScene = new ScrollScene({
      triggerElement: '.site-content',
      triggerHook: 0.9,
      duration: 300
    }).setTween(tween).addTo(parallaxController);
    videoOnScroll = document.getElementById('video-on-scroll');
    if (videoOnScroll) {
      myPlayer = videojs('video-on-scroll');
      myPlayer.controls(false);
      videoOnScrollScene = new ScrollScene({
        triggerElement: '.video-on-scroll',
        duration: $(window).height()
      }).addTo(videoOnScrollController);
      videoOnScrollScene.on('enter', function(e) {
        myPlayer.play();
      });
      videoOnScrollScene.on('leave', function(e) {
        myPlayer.pause();
      });
    }
    scrollToController.scrollTo(function(newpos) {
      TweenMax.to(window, 0.5, {
        scrollTo: {
          y: newpos
        }
      });
    });
    $(document).on('click', 'a[href^=#]', function(e) {
      var id;
      id = $(this).attr('href');
      if ($(id).length > 0) {
        e.preventDefault();
        scrollToController.scrollTo(id);
      }
    });
  });

}).call(this);
