// Generated by CoffeeScript 1.8.0
(function() {
  var onScroll;

  $(document).ready(function() {
    var $navSectionRef, $sectionNav;
    $sectionNav = $('.header');
    $navSectionRef = $('.smooth-scroll a');
    $(document).on('scroll', onScroll);
    $navSectionRef.on('click', function(e) {
      var $target, target;
      e.preventDefault();
      target = this.hash;
      $target = $(target);
      $(target).velocity('scroll', {
        duration: 300,
        offset: 7
      });
    });
  });

  onScroll = function(e) {
    var $navSectionRef, $scrollPos;
    $navSectionRef = $('.smooth-scroll a');
    $scrollPos = $(document).scrollTop();
    $navSectionRef.each(function() {
      var $currLink, $currLinkParent, $refElement;
      $currLink = $(this);
      $currLinkParent = $currLink.parent();
      $refElement = $($currLink.attr('href'));
      if ($refElement.position().top <= $scrollPos && $refElement.position().top + $refElement.height() > $scrollPos) {
        $currLink.addClass('active');
      } else {
        $currLink.removeClass('active');
      }
    });
  };

}).call(this);
