// Generated by CoffeeScript 1.8.0
(function() {
  var $navSectionRef, onScroll;

  $(document).ready(function() {
    var $navSectionRef, $sectionNav, $toTop;
    $sectionNav = $('.header');
    $navSectionRef = $('.smooth-scroll a');
    $toTop = $('.to-top');
    $(document).on('scroll', onScroll);
    $navSectionRef.on('click', function(e) {
      var $target, target;
      e.preventDefault();
      target = this.hash;
      $target = $(target);
      $(target).velocity('scroll', {
        duration: 700,
        offset: 7
      });
    });
    $toTop.click(function(e) {
      e.preventDefault();
      $('html').velocity('scroll', {
        duration: 700,
        offset: 0
      });
    });
  });

  $navSectionRef = $('.smooth-scroll a');

  onScroll = function(e) {
    var $scrollPos;
    $scrollPos = $(document).scrollTop();
    $navSectionRef.each(function() {
      var $currLink, $currLinkParent, $refElement;
      $currLink = $(this);
      $currLinkParent = $currLink.parent();
      $refElement = $($currLink.attr('href'));
      if ($refElement.position().top <= $scrollPos && $refElement.position().top + $refElement.height() > $scrollPos) {
        $currLink.addClass('active');
      }
      if ($refElement.selector === '#video-wrapper-team') {
        setTimeout(function() {
          var player;
          player = videojs('example_video_1');
          return player.play();
        }, 3000);
      } else {
        $currLink.removeClass('active');
      }
    });
  };

}).call(this);
