// Generated by CoffeeScript 1.8.0
(function() {
  var $header, $headerOff, $headerScrollRef, onScroll;

  $(document).ready(function() {
    var $navSectionRef, $sectionNav, $toTop;
    $sectionNav = $('.header');
    $navSectionRef = $('.smooth-scroll a');
    $toTop = $('.to-top');
    $(document).on('scroll', onScroll);
    $navSectionRef.on('click', function(e) {
      var $target, target;
      e.preventDefault();
      target = this.hash;
      $target = $(target);
      $(target).velocity('scroll', {
        duration: 700,
        offset: 7
      });
    });
    $toTop.click(function(e) {
      e.preventDefault();
      $('html').velocity('scroll', {
        duration: 700,
        offset: 0
      });
    });
  });

  $headerScrollRef = $('.header-scroll a');

  $header = $('.header');

  $headerOff = $('#header-off');

  onScroll = function(e) {
    var $scrollPos;
    $scrollPos = $(document).scrollTop();
    $headerScrollRef.each(function() {
      var $currLink, $currLinkParent, $refCalc, $refElement, $selector, $top;
      $currLink = $(this);
      $currLinkParent = $currLink.parent();
      $refElement = $($currLink.attr('href'));
      $selector = $refElement.selector;
      $top = $refElement.position().top - 140;
      $refCalc = $top <= $scrollPos && $top + $refElement.height() > $scrollPos;
      if ($refCalc) {
        $currLink.addClass('active');
        if ($selector === '#video-wrapper-team') {
          setTimeout(function() {
            var player;
            player = videojs('example_video_1');
            return player.play();
          }, 3000);
        }
      } else {
        $currLink.removeClass('active');
      }
    });
    if ($scrollPos <= 0) {
      $header.removeClass('header-off');
    } else if ($headerOff.hasClass('active')) {
      $header.removeClass('header-off');
    } else {
      $header.addClass('header-off');
    }
  };

}).call(this);
